name: Build-Lean-lede
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'lean-lede/x86_64/.config'
  schedule:
        - cron: 0 */6 * * *

jobs:
  
  MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
          LEDE_FILE_NAME: ${{ secrets.LEDE_FILE_NAME }}
          LEDE_SCP_PASSWORD: ${{ secrets.LEDE_SCP_PASSWORD }}
      run: |
        cd bin/
        zip -r -o -q -9 "$LEDE_FILE_NAME" . -i *
        curl -fsSL https://raw.githubusercontent.com/dond2008/My-action/master/lean-lede/scpUpload.sh >scpUpload.sh
        chmod 775 scpUpload.sh
        ./scpUpload.sh "$LEDE_FILE_NAME" "$LEDE_SCP_PASSWORD"
        echo "Upload success!"
        #bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)
        bash <(curl -fsSL https://raw.githubusercontent.com/dond2008/My-action/master/lean-lede/prenv.sh)
        
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede
        
    - name: Download and Load custom configuration
      run: |
        curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: Download package
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        
    - name: When Multi-core compile failure will be rollback to Single core compile
      run: |
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j2 || make -j1 V=s
        sudo df -h
        
    - name: Only Upload Packages to Download Station
      if: success()
      run: |
        cd bin
        zip -r -o -q -9  mt7621-Package.zip . -i *.ipk
        
    - name: Upload firmware to Download Station (Without packages)
      if: success()
      run: |
        cd bin/targets/*/*
        zip -r -o -q -9 "$LEDE_FILE_NAME" . -i *.bin
        curl -fsSL https://raw.githubusercontent.com/dond2008/My-action/master/lean-lede/scpUpload.sh >scpUpload.sh
        chmod 775 scpUpload.sh
        ./scpUpload.sh "$LEDE_FILE_NAME" "$LEDE_SCP_PASSWORD"
        echo "Upload success!"
